
spring.profiles.include=real-oauth
spring.jpa.show_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.h2.console.enabled=true
spring.session.store-type=jdbc
#spring:
#
#    #  devtools:
##    livereload:
##      enabled: true
##
##  freemarker:
##    cache: false
#
#    jpa:
#        show-sql: true
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#
#    h2:
#        console:
#            enabled: true
#
#
#    mustache:
#        prefix: file:///C:\Users\Administrator\git\book\projects\freelec-springboot2-webService\src\main\resources\templates
#        cache: false
#
#    resources:
#        static-locations: file:///C:\Users\Administrator\git\book\projects\freelec-springboot2-webService\src\main\resources\static
